development:
  adapter: postgresql
  encoding: unicode
  database: myflix_development
  pool: 5
  username: tho
  password: asian1 

test:
  adapter: postgresql
  encoding: unicode
  database: myflix_test
  pool: 5
  username: tho
  password: asian1
